### ISSUE TITLE
Combining both background & background-image

### ISSUE THREAD

**Issue by Yokocapolo** [gruntjs/grunt-contrib-cssmin#102]
`background` and `background-image` are being combined into just `background`. Which is cause problems for me. I need the two separate for svg fallback as browsers that can't handle multiple background images can't handle svgs either. But at the minute I'm only getting this output:

```
img1 {
    background:url(image.svg), none no-repeat;
}
```

When I need:

```
.img1 {
    background: url(image.png);
    background-image:url(image.svg), none;
    background-repeat: no-repeat;
}
```

Could you please fix or provide an option to toggle this?

**Comment by chungmeow** [comment]
nvm, I went ahead and read the README.md associated with our version..
