### ISSUE TITLE
CleanCSS "sourceMap" option isn't working

### ISSUE THREAD

**Issue by xiehan** [gruntjs/grunt-contrib-cssmin#155]
I was pretty excited when the new version upgraded clean-css to v3.0.1 so we can finally generate CSS sourcemaps, but I can't seem to get it to work.

I'm doing:

    cssmin: {
      options: {
        sourceMap: true,
        target: 'release/css'
      },
      target: {
        files: [{
          expand: true,
          cwd: 'release/css',
          src: ['*.css', '!*.min.css'],
          dest: 'release/css',
          ext: '.min.css'
        }]
      }
    }

The minified CSS files are created just fine, but no sourcemaps are generated.

I have no experience writing or debugging Grunt plugins so I have no idea where the problem lies. However, I installed CleanCSS globally so I could use its CLI, and I managed to generate source maps perfectly from the command line, so the problem doesn't appear to be with CleanCSS as far as I can tell.

**Comment by robneu** [comment]
+1 

I also couldn't get this working. If it's not an actual issue with the grunt plugin, some documentation on how to create source maps correctly would be really helpful.

**Comment by shinnn** [comment]
PR welcome.

**Comment by danny-englander** [comment]
According to this issue, https://github.com/gruntjs/grunt-contrib-cssmin/issues/58, this is supposed to be fixed now but I could not get it to work either. Min files are generated but with no sourcemaps using code similar to that of the OP.

**Comment by sindresorhus** [comment]
Fixed in 0.12.0.

**Comment by danny-englander** [comment]
This works great! Thank you.
