### ISSUE TITLE
Invalid CSS output

### ISSUE THREAD

**Issue by jkieley** [gruntjs/grunt-contrib-cssmin#158]
input:
https://gist.github.com/jkieley/18af3bf527a7fc635775
output:
https://gist.github.com/jkieley/ad167fc6fefa41c5317e

Rule I know is broken:
#stream-loading

works fine with the regular css file, when using the minified file the styles break.

Here is our config:
https://gist.github.com/jkieley/a30eab7c3d52261e6beb

**Comment by jkieley** [comment]
in browser syntax highlight stops around column 961 one minified file. The syntax error maybe somewhere around there

**Comment by sindresorhus** [comment]
From the readme:

> **Issues with the output should be reported on the clean-css [issue tracker](https://github.com/GoalSmashers/clean-css/issues).**

**Comment by xtianus79** [comment]
I have a similar problem.  what can I do?

**Comment by netbek** [comment]
@xtianus79 Perhaps try the `advanced` option, or one or more of the others listed in the [clean-css readme](https://github.com/jakubpawlowicz/clean-css/blob/master/README.md#how-to-use-clean-css-programmatically), in your Gruntfile, e.g.

```
cssmin: {
  options: {
    advanced: false
  }
}
```
