### ISSUE TITLE
s0 option not working

### ISSUE THREAD

**Issue by Thandriel** [gruntjs/grunt-contrib-cssmin#164]
Trying to minify bootstrap.min.css file with s0 option.

            cssmin: {
            options: {
                s0: true
            },
            target: {
                files: {
                    'public/css/bootstrap.min.css': ['public/css/bootstrap.min.css']
                }
            }
        }

As a result, important commentary on top of .css file presists.

**Comment by sindresorhus** [comment]
From the readme:

> **Issues with the output should be reported on the clean-css [issue tracker](https://github.com/GoalSmashers/clean-css/issues).**

**Comment by Thandriel** [comment]
With CLI clean-css it works, so I assumed the problem is going to be here. Thank you anyway. I'm going to report to the clean-css issue tracker.
