### ISSUE TITLE
Blank spaces in output file

### ISSUE THREAD

**Issue by godlovesugly** [gruntjs/grunt-contrib-cssmin#169]
What am I doing wrong here? I have a normal css file, but the output has blank spaces between characters, like this:

`��  /* Reset ================================================================================= */ * { margin:0; padding:0;: } body {  color:#999999;   text-align:center;   font-size: 12px;   line-height: 1.5em;:`

**Comment by sindresorhus** [comment]
From the readme:

> Issues with the output should be reported on the clean-css issue tracker.
