### ISSUE TITLE
parentheses dropped on calc

### ISSUE THREAD

**Issue by koolkatwebdesigns** [gruntjs/grunt-contrib-cssmin#171]
.masonry-item {
  width: 33.33%;
  width: -webkit-calc( ( 100% - 12px ) / 3 );
  width: -moz-calc( ( 100%  - 12px) / 3 );
  width: calc( ( 100%  - 12px) / 3 );
}

becomes:
masonry-item{width:33.33%;width:-webkit-calc(100% - 12px) / 3);width:-moz-calc(100% - 12px) / 3);width:calc(100% - 12px) / 3)}

the above results in invalid CSS so the calc is ignorned

**Comment by sindresorhus** [comment]
Not the right place. See readme.

**Comment by koolkatwebdesigns** [comment]
Sorry, I reposted on clean css git. It's already been fixed
