### ISSUE TITLE
0.12.0 broke rebase?

### ISSUE THREAD

**Issue by kokarn** [gruntjs/grunt-contrib-cssmin#172]
Hello!

Great to see sourceMaps finally working!
However, it seems that 0.12.0 broke the ```rebase``` option.

grunt-contrib-cssmin <= 0.11.0 works as expected. ```src: url("fonts/font.eot");``` stays the same, but in 0.12.0 it get's changed to ```src: url("www/css/fonts/font.eot");```

Config used
```
cssmin: {
    default: {
        options : {
            compatibility: 'ie8',
            rebase: false,
            advanced: false
        },
        src: [ 'www/css/style.prefix.css' ],
        dest: 'www/css/style.min.css'
    }
}
```

**Comment by sindresorhus** [comment]
Pretty sure this is with clean-css. Can you try reinstalling the 0.11.0 version and see if it happens there too?

**Comment by kokarn** [comment]
I have tried going back and forth between 0.12.0 and 0.11.0 in the package.json, doing a rm -rf node_modules/ and reloading grunt in between and re-running the exact same configuration.

It does change the output with only that single digit changing.

**Comment by sindresorhus** [comment]
Yeah, looks like https://github.com/gruntjs/grunt-contrib-cssmin/pull/170 introduced that bug.

**Comment by kokarn** [comment]
Wow, that was super quick.

Big thank you dude!
