### ISSUE TITLE
File names with more than one period

### ISSUE THREAD

**Issue by Mottie** [gruntjs/grunt-contrib-cssmin#175]
I have a directory with mixed file names, but it appears that only files named using this format are ignored:

    theme.{name}.css

I think it's because the file name has two periods in it. If I rename the files to `theme-{name}.css` it will get processed.

Just in case you need to see it, I set up my grunt file with these settings:

```js
cssmin: {
	target: {
		files: [{
			expand: true,
			flatten: true,
			cwd: 'css',
			src: ['theme.*.css', '*.css'],
			dest: 'dist/css',
			ext: '.min.css'
		}]
	}
}
```

I don't know if this is an issue with `grunt-contib-cssmin` or `clean-css`, so I thought I'd start here first.

-----

*Update*: Actually to clarify, I think it ignores the content between the first & last periods.

I have the following files that do get converted:

* `dragtable.mod.css` becomes `dragtable.min.css`
* `filter.formatter.css` becomes `filter.min.css`
* `theme.black-ice.css` becomes `theme.min.css`
* `jquery.tablesorter.pager.css` becomes `jquery.min.css`

The rest of the files are not being added because of duplicate file names

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

-

http://stackoverflow.com/questions/16697344/configure-grunt-file-name-matching-for-files-with-multiple-dots/16697852#16697852
