### ISSUE TITLE
Why is banner option removed?

### ISSUE THREAD

**Issue by dragonfish-au** [gruntjs/grunt-contrib-cssmin#176]
Couldn't figure out why.

**Comment by sindresorhus** [comment]
Read the relevant commit: https://github.com/gruntjs/grunt-contrib-cssmin/commit/985b3d8cb60dd45ff9eaa472662ebea69d3b5eb0

**Comment by dragonfish-au** [comment]
Thanks for pointing out. I thought about it as well. Just could find out why online.
