### ISSUE TITLE
0.12.1 messes with url() fields

### ISSUE THREAD

**Issue by thanpolas** [gruntjs/grunt-contrib-cssmin#179]
Minifying standard distributed bootstrap css file, the following line:

```css
  src: url('../fonts/glyphicons-halflings-regular.eot');
```

Gets converted to this:

```css
  src: url(front/static/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot);
```

As if it's performing path resolution from the project's root, prepending the `front/static/bower_components/bootstrap/dist` part.

This behavior is not present in 0.11.0

**Comment by ArtemFitiskin** [comment]
Absolutly agree with this issue. Since 0.12.x relative urls was crashed.

**Comment by cmmarslender** [comment]
Agree. This breaks all my url() rules as well. Lots of ../../.. get stripped away :(

**Comment by vladikoff** [comment]
dup of https://github.com/gruntjs/grunt-contrib-cssmin/issues/173
