### ISSUE TITLE
updating to 0.12 breaks asset replacement in css

### ISSUE THREAD

**Issue by sylvain-hamel** [gruntjs/grunt-contrib-cssmin#181]
# tl;td;

My build process takes files in my `/static` folder and create a `/dist` folder.

The issue is that in my resulting (reved/minified) css file (`/dist/css/891374h.main.css`), the paths to the images are no longer replaced with the *dist* location. So the css file refers to `img/check.jpg` (original location) instead of `../img/check.jpg`.

Downgrading to `grunt-contrib-cssmin@0.11.0` fixes the issue.

So has there been an accidental breaking change in 0.12?

# More context...

A while ago, I have scaffolded a project using `yeoman angular` and it has been working well ever since. I have only tailored the build process a bit but I must admin on don't fully understand how these tools work. I know the build process relies on these packages.

```
grunt-contrib-clean
grunt-contrib-concat
grunt-contrib-copy
grunt-contrib-cssmin
grunt-contrib-htmlmin
grunt-contrib-imagemin
grunt-contrib-uglify
grunt-ngmin
grunt-rev
grunt-svgmin
grunt-usemin
```

I voluntarily don't freeze tool versions in the `package.json` for this build. This way I always have the latest version of the tools.

**Comment by MSNK** [comment]
I have the same problem. The ```noRebase``` option became ```rebase``` in ```clean-css``` v3 so the default value is now reversed. Adding ```rebase: false``` to your cssmin options should help.
