### ISSUE TITLE
Task converts my paths, how I can stop it? 

### ISSUE THREAD

**Issue by Pestov** [gruntjs/grunt-contrib-cssmin#182]
So, for example I have the next path: `url('../images/bg.png')`. And on output I got `assets/images/ip-cover@2x.jpg`. At result all paths for index.html looks like `assets/css/assets/images'. Just a couple week ago I don't have this proble. Is it css-clean update?

     cssmin: {
            target: {
                files: [{
                    expand: true,
                    src: ['*.css', '!*.min.css'],
                    dest: 'assets/css',
                    ext: '.min.css'
                }]
            }
        },

**Comment by sindresorhus** [comment]
Please look at the open issues before opening one...
