### ISSUE TITLE
Banner option

### ISSUE THREAD

**Issue by 4Digits** [gruntjs/grunt-contrib-cssmin#184]
Is there a specific reason why the banner option was removed?

I found that quiet useful and more streamlined rather than having to add an additional plugin now just for the banner. 

grunt-contrib-uglify still has that option.

**Comment by sindresorhus** [comment]
It's all in the commit text: https://github.com/gruntjs/grunt-contrib-cssmin/commit/985b3d8cb60dd45ff9eaa472662ebea69d3b5eb0

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/grunt-header
https://github.com/mattstyles/grunt-banner
