### ISSUE TITLE
report not shown

### ISSUE THREAD

**Issue by kaelhem** [gruntjs/grunt-contrib-cssmin#185]
The report option seems to be broken. Nothing is displayed. Same result with 'min' or 'gzip'.
I'm using version 0.12.2

**Comment by XhmikosR** [comment]
It is shown in verbose mode. Ref https://github.com/gruntjs/grunt-contrib-cssmin/commit/cc71ae9d89ea5415bc4d5fd4ecd5ef2ae72d65cd

I disagree with that change but @sindresorhus just did them in many of the contrib plugins...

**Comment by sindresorhus** [comment]
@XhmikosR Well it was changed because many people didn't like us spamming their terminal. So some people will be unhappy no matter what we default to.

Open a ticket on grunt to get consensus on what to do for all grunt-contrib plugins: https://github.com/gruntjs/grunt I'm not interested in constantly having to change or having inconsistent behaviour between the plugins.

**Comment by XhmikosR** [comment]
I agree we can't make everyone happy, that is for sure.

But this info isn't bloat; it's the only way the user knows something really happens and verbose has so many info that beats the point.

Personally, I do believe we are going to the right direction, but we shouldn't hide everything under normal run. We should output useful info without bloating the output.

I'll open a new issue.

**Comment by kaelhem** [comment]
Hum, that's weird, but I understand.
The report option shouldn't be set to false by default in that case ?
However, that should be added to the doc.

**Comment by gapipro** [comment]
Well --verbose mode is a real spam. But report (497.65 kB → 483.77 kB → 88.77 kB) info is really useful and hard to notice in that spam.

Wouldn't be better to move it to normal grunt.log and add another option to report option like "none", so users who don't like it can hide it. Also it saves some CPU cycles.

**Comment by XhmikosR** [comment]
We really need to make an issue in the grunt repo to discuss this and come to an agreement.

I still believe we should show the size in normal output since it's **useful** information and not bloat. Also, not giving any feedback on success is bad.

**Comment by vladikoff** [comment]
Yeah there should be some output, at least for files created.

**Comment by philippsimon** [comment]
I also just wondered why there is no message for cssmin at the end (like for all other plugins i use).
It would be really great to have a message like this at the end:
`>> x files created.`

**Comment by vladikoff** [comment]
If anyone has time to send a pull request please do so, otherwise I will try to get to this in a few days :cake:

**Comment by philippsimon** [comment]
i'll do it

**Comment by gapipro** [comment]
Well size report is still not visible...
