### ISSUE TITLE
negative padding value will invalidate all padding for an element

### ISSUE THREAD

**Issue by ayasdi** [gruntjs/grunt-contrib-cssmin#187]
I have a padding rule for an element that looks like this:

```
div.element {
  padding-left: 6.75rem
  padding-right: 6.75rem
  padding-top: 0.9375rem
  padding-bottom: -0.3125rem
}
```

Those values result from SASS calculations so the negative, invalid value for padding-bottom was not intended, but it is a possibility in which case we're fine with no padding-bottom being applied, as is the browser.

When cssmin attempts to concatenate those padding rules into one rule, it looks like this, thus getting invalidated in the browser:

```
padding: 0.9735rem 6.675rem -0.3125rem
```

We can just prevent the value from becoming negative in SASS, but I'd expect the same behavior in CSS between the minified and non-minified versions.

**Comment by vladikoff** [comment]
Please file this bug here https://github.com/jakubpawlowicz/clean-css/issues
