### ISSUE TITLE
grunt-contrib-cssmin creating min.css empty files

### ISSUE THREAD

**Issue by scuenca** [gruntjs/grunt-contrib-cssmin#189]
I have the following configuration:
```js
cssmin: {
      target: {
        files: [{
          expand: true,
          cwd: css_dir,
          src: ['**/*.css',  '**/!*.min.css'],
          dest: css_dir,
          ext: '.min.css'
        }]
      }
    },
```
I am runnit this grunt task with ANT,

When i execute the tasks the result is:

[exec] ←[4mRunning "cssmin:target" (cssmin) task←[24m
[exec] ←[32mDone, without errors.←[39m

And the output directory has the .min.css files but those files are all empty.

**Comment by XhmikosR** [comment]
#191
