### ISSUE TITLE
grunt-contrib-cssmin creating min.css empty files

### ISSUE THREAD

**Issue by scuenca** [gruntjs/grunt-contrib-cssmin#191]
I have the following configuration with the cssmin version 0.12.2:

```js
cssmin: {
      target: {
        files: [{
          expand: true,
          cwd: css_dir,
          src: ['**/*.css',  '**/!*.min.css'],
          dest: css_dir,
          ext: '.min.css'
        }]
      }
    },
```
I am runnit this grunt task with ANT,

When i execute the tasks the result is:

[exec] ←[4mRunning "cssmin:target" (cssmin) task←[24m
[exec] ←[32mDone, without errors.←[39m

And the output directory has the .min.css files but those files are all empty.
The same configuration with css-min version 0.11.0 works correctly. There is a problem between 0.11.0 and 0.12.2.

The complete explanation of the problem is here:
https://github.com/jakubpawlowicz/clean-css/issues/467

**Comment by jakubpawlowicz** [comment]
It seems not likely to be attributed to clean-css 3.1 upgrade since the API is same and @scuenca file - see https://github.com/jakubpawlowicz/clean-css/issues/467#issuecomment-76361402 - minifies fine with `cleancss` binary.

I'm not familiar with the plugin internals, but do you report any errors clean-css is raising?

**Comment by XhmikosR** [comment]
How about using `src: ['**/*.css',  '!**/*.min.css'],`?

**Comment by infostreams** [comment]
I had this same problem yesterday, but had the fortunate circumstance that I was accidentally running 2 cssmin operations in sequence, one referencing a relative CSS path, and the other referencing an absolute CSS path. The one that had a relative CSS path correctly produced a non-zero minified CSS file, but the one with the absolute path produced an empy CSS file (even though the path itself was correct). Not sure if this is related, and aware that this is not StackOverflow - but perhaps this might help you guys figure out what's going on here.

**Comment by evoactivity** [comment]
Also had to downgrade to 0.11.0, output is absolutely fine with 0.11.0, but it is completely empty when using the latest version.

task setup like so

    cssmin: {
        dest: {
            options: {
                report: 'gzip',
                root: __dirname.replace('assets','')
            },
            files: [{
                src: ['styles/tmp/style.css'],
                dest: 'styles/style.min.css'
            }]
        }
    }

**Comment by ademarre** [comment]
I was hit by this also and have had to revert to 0.11.0. My config is very similar to @scuenca's

**Comment by gunjanpatidar** [comment]
Same issue with 0.12.2

**Comment by efender** [comment]
I have same problem with 0.12.*

**Comment by freezy** [comment]
Same here. Reverting to 0.11.

**Comment by smbeiragh** [comment]
Same here. Reverting to 0.11.

**Comment by tgyou** [comment]
same ... 0.12.2

**Comment by luisalves73** [comment]
How do we revert?

**Comment by evoactivity** [comment]
@luisalves73 change the version in your `package.json` and re-run `npm install`

**Comment by luisalves73** [comment]
@evoactivity thanks!
