### ISSUE TITLE
grunt-contrib-cssmin adding space after closing Parentheses

### ISSUE THREAD

**Issue by koriguy** [gruntjs/grunt-contrib-cssmin#193]
since version 0.11, when I have this class:

.wrapper .list:nth-child(2).second{
  background-color: red;  
}
css min will add a space after parentheses and will produce:
.wrapper .list:nth-child(2) .second{background-color:red;}
(see space between list:nth-child(2) and .second

example here: 
http://jsbin.com/qabajiguwu/1/edit?html,css,output

**Comment by sindresorhus** [comment]
https://github.com/gruntjs/grunt-contrib-cssmin/issues/192#issuecomment-76739308
