### ISSUE TITLE
Change css path root.

### ISSUE THREAD

**Issue by ben-gibson** [gruntjs/grunt-contrib-cssmin#195]
I have the following setup

cssmin: {
        options: {
            rebase: true,
        },
        concat: {
            files: {
                'dist/app.css': [
                    'tmp/*.css',
                    'app/theme/css/vendors/fontello.css',
                    'app/theme/js/vendors/revolution/css/settings.css',
                    'app/theme/css/styles.css',
                    'app/theme/css/media-queries.css',
                    'app/app.css'
                ]
            }
        },
        min: {
            files: [{
                src: 'dist/app.css',
                dest: 'dist/app.css'
            }]
        }
    },

The issue is the css paths are changed to 'app/theme/images/..' or 'app/images..' however everything is moved into a dist folder for production so I need the paths to be '/theme/images/' and '/images'. I have tried every possible option but nothing seems to be able to remove app/ from the path :(

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
