### ISSUE TITLE
Wrong output filename for input files containing a period

### ISSUE THREAD

**Issue by jt000** [gruntjs/grunt-contrib-cssmin#197]
Minifying a filename containing a period saves as a file only up to the first period. Should only strip off the extension.

For example, with the below config settings...

```javascript
cssmin: {
  target: {
    files: [{
      expand: true,
      cwd: '<%= config.dest %>/assets/css',
      src: ['*.css', '!*.min.css'],
      dest: '<%= config.dest %>/assets/css',
      ext: '.min.css'
    }]
  }
},
```

...a file named "my.styles.css" will be saved as "my.min.css" instead of "my.styles.min.css".

**Comment by sindresorhus** [comment]
This too has been answered a gadzillion times. Google is your friend.

http://stackoverflow.com/questions/16697344/configure-grunt-file-name-matching-for-files-with-multiple-dots/16697852#16697852
