### ISSUE TITLE
Passing "sourceMapInlineSources" option to clean-css not working

### ISSUE THREAD

**Issue by ColdFusionWI** [gruntjs/grunt-contrib-cssmin#202]
According to the docs, options are passed to clean-css.  Passing the "sourceMapInlineSources: true" clean-css option isn't working. Source map generation is working flawlessly; I just can't seem to get my source map to include the source of my files similar to how grunt-contrib-uglify does with it's "sourceMapIncludeSources: true" option.

``` javascript
cssmin : {
    css:{
        files: {
            'css/combined.min.css': cssSources
        },
        options: {
            sourceMap: true,
            sourceMapInlineSources: true
        }
    }
}
```

**Comment by thealjey** [comment]
it's bug in clean-css, not grunt-contrib-cssmin

**Comment by moderndegree** [comment]
try `sourceMapInlineSources`
