### ISSUE TITLE
v0.12.2 mangles CSS

### ISSUE THREAD

**Issue by jonsuh** [gruntjs/grunt-contrib-cssmin#205]
When I run task `grunt cssmin` (0.12.2) it mangles my CSS; however, when I use a past installation of the same version of `cssmin`, it doesn't mangle the CSS.

    OS X Yosemite 10.10.2
    nvm version 0.24.0
    node version 0.12.2
    npm version 2.7.4

I did a bit of homework, and I think the source of the problem is that `npm install grunt-contrib-cssmin` installs the incorrect version of `clean-css` (3.1.0 instead of 3.0.10).

- When I install a fresh version of `cssmin` to my local project by running `npm install grunt-contrib-cssmin -D`, package.json has the correct version (^0.12.2).
- When I look in `node_modules/grunt-contrib-cssmin/package.json`, it references the correct version of `clean-css` (^3.0.1)
- However, when I look in `node_modules/grunt-contrib-cssmin/clean-css/package.json`, the version installed is 3.1.0.

When I compare that another installation of `grunt-contrib-cssmin` in another project folder, `node_modules/grunt-contrib-cssmin/clean-css/package.json` has version 3.0.10.

- When I run `grunt cssmin` from the new project folder with `clean-css` 3.1.0, it mangles my CSS.
- When I run `grunt cssmin` from the old project folder with `clean-css` 3.0.10, it works fine.

Both projects have `"grunt-contrib-cssmin": "^0.12.2",` in the package.json, but the version of `clean-css` differs.

I tried cleaning my npm cache (`npm clean cache` and `rm -rf ~/.npm`) and reinstalling via `npm install grunt-contrib-cssmin`, but still no luck.

The only way to fix it is to delete the `grunt-contrib-cssmin folder` in `node_modules` and replace it with the one from the other project that has `clean-css` 3.0.10.

**Comment by sindresorhus** [comment]
Well, that sounds like an issue with `clean-css` 3.1.0. `^3.0.1` will match `3.1.0`, so that's the correct behaviour. Not sure why you're seeing different results, but that's not really relevant to this issue.

Look through the `clean-css` issue tracker and open an issue there.

Recommended reading: https://nodesource.com/blog/semver-tilde-and-caret
