### ISSUE TITLE
Duplicate media query

### ISSUE THREAD

**Issue by indaam** [gruntjs/grunt-contrib-cssmin#206]
Hi,
Iam use scss to develop css, and I create many file, ex;
header.scss
main.scss
In the file, I write each media query.
And the output css like this
// header.scss
@media screen and (max-width:640px){.main{float: none;width: auto}}
// header.scss
@media screen and (max-width:640px){.header{float: none;width: 90%}}

How to minify like this
@media screen and (max-width:640px){.main{float: none;width: auto;}.header{float: none;width: 90%}}}

Thanks so much

**Comment by XhmikosR** [comment]
>Issues with the output should be reported on the clean-css [issue tracker](https://github.com/GoalSmashers/clean-css/issues).
