### ISSUE TITLE
cssmin fails with clean-css 3.2.0 when options.sourceMap === true

### ISSUE THREAD

**Issue by limscoder** [gruntjs/grunt-contrib-cssmin#208]
Repro (fails against bootstrap.css v3.1.1):

    options: {
        sourceMap: true
    }

build works correctly with clean-css 3.1.9 and fails with error with clean-css 3.2.0.

    >>> TypeError: Arguments to path.join must be strings

I don't know if this is an issue with clean-css or the integration between grunt-contrib-cssmin and clean-css.
Possibly pin clean-css version until the issue is fixed?

**Comment by sindresorhus** [comment]
I tried reproducing with Bootstrap, but both `clean-css` 3.2.0 and 3.2.2 works fine for me. Submit a failing test and I'll look more into it.

**Comment by danny-englander** [comment]
I just ran into this issue when installing my node_modules on a new machine. The install is from a package.json file that works fine on other machines and we have the versions locked down as well. 

I ran grunt --force -v to print out the full error:
https://gist.github.com/danny-englander/f7c00e6253726800498e

Other than these errors above everything looks ok and if I remove cssmin, grunt works without issue. Note I am not using bootstrap nor clean-css. I also tried removing Node.js and reinstalling as well as reinstalling grunt cli but still no joy. I can't imagine what would have changed, I compared and the grunt-contrib-cssmin versions are the same on both machines.

**Comment by danny-englander** [comment]
Upon further testing, if I do `sourceMap: false,` within my cssmin function in my gruntfile.js, everything is fine. However, I don't get why setting sourceMap to true would break this, it had been working fine all along with this setup.

**Comment by danny-englander** [comment]
Sorry to keep posting but I installed the Node version that was on my other machine v0.10.35 and that fixes this. On the new machine with the error, I had v0.12.2 so reverting back seems to do the trick. I wonder if it has anything to do with the changes here: https://github.com/joyent/node/wiki/API-changes-between-v0.10-and-v0.12 ?

**Comment by bhamodi** [comment]
Should be fixed now with v3.3 @limscoder and @danny-englander. :+1:

**Comment by danny-englander** [comment]
This is now working nicely, thanks!

**Comment by bhamodi** [comment]
Awesome! No problem.
