### ISSUE TITLE
Question about cssmin

### ISSUE THREAD

**Issue by magixsource** [gruntjs/grunt-contrib-cssmin#209]
Hey,
I have three file
  selectize.default.css
  selectize.pagination.css
  selectize.patch.css

and i want min them
so

cssmin:{
            min:{
                files:[
                    {
                        expand:true,
                        cwd:'css',
                        src:['selectize.default.css','selectize.pagination.css','selectize.patch.css','!*.min.css'],
                        dest:'release/css',
                        ext:'.min.css'
                    }
                ]
            }
        }

but result is only one file named selectize.min.css
i don't want they min in only one file,i need three. 
How to config it ?

Thanks very much.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
