### ISSUE TITLE
Granular Compatibility Options

### ISSUE THREAD

**Issue by soluml** [gruntjs/grunt-contrib-cssmin#210]
I'm needing to turn off spaces after closing braces in clean-css. Clean-css lets you do this through properties.spaceAfterClosingBrace: https://github.com/jakubpawlowicz/clean-css#how-to-set-compatibility-mode

I tried adding a properties object with spaceAfterClosingBrace to false in the options object, but that didn't seem to do anything.  Is it possible to target the compatibility options with this plugin?

**Comment by wawyed** [comment]
You can do it, you need to use the syntax as defined in the docs you quoted, so for example to disable one property:
```
cssmin: {
      files: {
        options: {
          compatibility: '*,-properties.zeroUnits'
        },
```

That should work for you. :)

**Comment by soluml** [comment]
Awesome thanks, that seems to work!
