### ISSUE TITLE
grunt console inform about files produced (same as grunt:uglify)

### ISSUE THREAD

**Issue by tkoomzaaskz** [gruntjs/grunt-contrib-cssmin#211]
I think it'd be good if grunt plugins would work the same way. I like that [uglify task](https://github.com/gruntjs/grunt-contrib-uglify) prints information about maps and files created. Unfortunately, cssmin task doesn't, as seen below:

![cssmin-missing-file-info](https://cloud.githubusercontent.com/assets/375027/7337920/12df4b50-ec3b-11e4-9f74-62ef7b233772.png)

I know I can turn `--verbose` on, but it is not a good solution, since:
* standards are good and grunt plugins should work the same way
* turning verbose print great amounts of output and it's not convenient to scan through all this if I only want to see, whether anything has been produced. In other words, I think that `grunt.log.ok("x files created")` should become a standard output of cssmin (that hardcoded string is just a simplification, of course)

----

uglify has done it like this: https://github.com/gruntjs/grunt-contrib-uglify/blob/master/tasks/uglify.js#L181-L185

**Comment by tkoomzaaskz** [comment]
Hmm, I've just seen that there is a similar code in cssmin task, but it's not available through npm even though I've got the right version: `0.12.2`. What is going on?

**Comment by sindresorhus** [comment]
People seems to split be split about this and I'm tired of having to change back and forth.

Get a decision made for all contrib plugins here and we can change them all to something common: https://github.com/gruntjs/grunt/issues

**Comment by tkoomzaaskz** [comment]
@sindresorhus just as you suggested, I opened an issue for discussion: https://github.com/gruntjs/grunt/issues/1318
