### ISSUE TITLE
background lost white space

### ISSUE THREAD

**Issue by qiangyee** [gruntjs/grunt-contrib-cssmin#212]
I have css like this
`.wrap_v_area{ background: #01101e url(../images/xxx.png) center no-repeat; height: 1225px;}`
after cssmin, it's change to 
`.wrap_v_area{background:url(../images/xxx.png)center no-repeat #01101e;height:1225px}`
It's lost white space between url and center. This lead to IE8 cannot parse the background style.
cssmin version:^0.12.2
grunt version: grunt-cli: The grunt command line interface. (v0.1.13)

**Comment by sindresorhus** [comment]
From the readme:

> **Issues with the output should be reported on the clean-css [issue tracker](https://github.com/GoalSmashers/clean-css/issues).**
