### ISSUE TITLE
Convert # css color to named color when minifying

### ISSUE THREAD

**Issue by smithery** [gruntjs/grunt-contrib-cssmin#215]
If you have in your css

 color: #ff0000;
 color: #00ff00;
 color:#0f0;

 and then minify the css, the value is converted to

 color:red;
 color:green;
 color:green;

 While this may make readability sense, it probably makes no programmatic sense on two levels: 1) depending on the color, the result is actually larger (defeats the minify) and you can't easily read it as your css is not effectively one line; 2) at the browser level, I would imagine the lookup mechanism for the color would be slower than if the hex number is used (I have no insight as to if this is true, however, just thinking about it, the coding would be faster and smaller for the hex conversion which the name color has to be converted to anyways).

Regarding the second case, I had an email discussion with an engineer who was able to test the parsing performance of the css and noted that parsing of the hex value was significantly faster than the named color. I would suggest either creating a mechanism to allow the exact color to be used rather than conversion. Please remember, that the css file can be cached on the client side so the download is no longer a factor. The parsing of the file now becomes the issue.

**Comment by sindresorhus** [comment]
> While this may make readability sense

This is for minifying CSS. Readability is not a concern.

> depending on the color, the result is actually larger (defeats the minify) and you can't easily read it as your css is not effectively one line;

This is the only valid point. It should only switch to color name if it's actually shorter. Can you open an issue here https://github.com/jakubpawlowicz/clean-css/issues/new for specifically that?

> I would imagine the lookup mechanism for the color would be slower than if the hex number is used (I have no insight as to if this is true, however, just thinking about it, the coding would be faster and smaller for the hex conversion which the name color has to be converted to anyways).

Nope. It's totally negligible.

http://c2.com/cgi/wiki?PrematureOptimization

**Comment by smithery** [comment]
Well, the engineer I referred to in the second case said the same thing. Then a couple of days, he actually did a test and found out he was wrong. So, I respectfully disagree with your "Nope". Unless you have looked at all the different browsers out there and know their decoding mechanism, that is not a valid response.
