### ISSUE TITLE
Compatibility issue IE9

### ISSUE THREAD

**Issue by Nehas1001** [gruntjs/grunt-contrib-cssmin#221]
I'm using cssmin to minify my css. I have tried including compatibility: 'ie9' as well as compatibility:true but during minification it is still removing IE9 hacks I have written.

This is how I have written my code
cssmin: {
    options: {
        compatibility:  true
    },

As well as I have tried 
cssmin: {
    options: {
        compatibility:  'ie9'
    },

Please tell me what other options I have to make it work with IE9.

Thanks

**Comment by jshemas** [comment]
Having the same problem.

**Comment by tobystokes** [comment]
Compatibility is set to ie9 by default, you would only need to specify that option for ie7/8.
https://github.com/jakubpawlowicz/clean-css#how-to-set-compatibility-mode

However, there are a few seperate issues in the latest versions of cssclean which may need tuning for old IE, in my experience. Simplest workaround is to downgrade grunt-contrib-cssmin to 0.9, which uses cssclean 2

**Comment by tobystokes** [comment]
I found adding
options: { restructuring: false }
helped fix some complex selector issues IE9 was having for me.

**Comment by XhmikosR** [comment]
You should report those issues upstream if they are still present.

**Comment by miukki** [comment]
options: { compatibility: 'ie9' , restructuring: false }  help restore IE9
