### ISSUE TITLE
css calc height fallback for older browsers

### ISSUE THREAD

**Issue by Ghostavio** [gruntjs/grunt-contrib-cssmin#223]
Hello, so I'm using the following in my code:
```
height: 100%;
height: calc(100% - 55px);
```
So for browsers without `calc` support, the first value should be taken, but cssmin is removing it and keeping just `height: calc(100% - 55px);`, there's anyway to keep this particular duplicated css attribute without disabling all the duplication removal, or maybe creating a rule for this specific case?
In case it's not possible, how would I completely disable the check for duplication on the grunt plugin?

Thanks.

**Comment by sindresorhus** [comment]
From the readme:

> **Issues with the output should be reported on the clean-css [issue tracker](https://github.com/GoalSmashers/clean-css/issues).**
