### ISSUE TITLE
Broken @import declaration

### ISSUE THREAD

**Issue by billykeyss** [gruntjs/grunt-contrib-cssmin#232]
I'm getting this error while running cssmin. I used yeoman and AngularJS generator to set up this project. As far as I can tell, mixins.less is from bootstrap as I don't use @import in any of my css files.

This is the error message I get.
Running "cssmin:generated" (cssmin) task
Warning: Broken @import declaration of "\mixins.less\" Use --force to continue.

Aborted due to warnings.

Adding 
    options: {
       processImport: false
    }
to the css task removes the error but then bootstrap isn't loaded in the final build. Is there a way to fix this issue?

**Comment by sindresorhus** [comment]
This task is for `CSS` not `LESS`:

> Warning: Broken @import declaration of "\mixins*.less*\" Use --force to continue.
