### ISSUE TITLE
Bug with "ext"

### ISSUE THREAD

**Issue by xsuchy09** [gruntjs/grunt-contrib-cssmin#233]
When filename contains more dots then ext is inserted after first dot - not at the end of file (before .css).

Example (ext is set to 'min.css'):
foo-1.0.2.css
output is:
foo-1.min.css

Please fixed it.

Before fix you can use this rename without ext option:
```
rename: function(dest, src) {
    return dest + src.replace('.css', '.min.css');
}
```

**Comment by vladikoff** [comment]
try `extDot` http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by xsuchy09** [comment]
Thanks, I didn't notice this option. I vote for "last" as default ... first as default is not good solution (IMHO) ...
