### ISSUE TITLE
@-webkit-keyframes Not Supported

### ISSUE THREAD

**Issue by ladjzero** [gruntjs/grunt-contrib-cssmin#237]
`@-webkit-keyframes` does not come to the output. cssmin discards it.

Does it relative to https://code.google.com/p/cssmin/issues/detail?id=26 ?

**Comment by ladjzero** [comment]
I think it should be reported to clean-css. Close.

**Comment by that1guy** [comment]
FYI.  https://github.com/jakubpawlowicz/clean-css/issues/663

Anyone found a solution to this yet?

**Comment by Clement-TS** [comment]
I assume this is still an issue with grunt-contrib-cssmin v2.1.0, at least the tool ignores it.
Example of my source code: 

```js
@-webkit-keyframes animScaleUp {
	0% {
		opacity: 0;
		-webkit-transform: translate3d(0,-50%,0) scale3d(0,0,1);
	}
	100% {
		opacity 1;
		-webkit-transform: translate3d(0,-50%,0) scale3d(1,1,1);
	}
}
```
the warning:

```sh
Running "cssmin:build" (cssmin) task
>> Invalid property name 'opacity 1;
>> 		-webkit-transform' at dist/style.css:2371:2. Ignoring.,Invalid property name 'opacity 1;
>> 		-webkit-transform' at dist/style.css:2383:2. Ignoring.
>> 1 file created. 91.01 kB → 59.67 kB
```
