### ISSUE TITLE
Stripping * in *:before

### ISSUE THREAD

**Issue by knynkwl** [gruntjs/grunt-contrib-cssmin#238]
Hey, just ran into this problem. when compressing my css file, it seems to strip `*` if it's in front of a sudo element.

`.some-element *:before` turns into `.some-element :before`

**Comment by sindresorhus** [comment]
From the readme:

> **Issues with the output should be reported on the clean-css [issue tracker](https://github.com/GoalSmashers/clean-css/issues).**
