### ISSUE TITLE
HTML break line on css rule content "}"

### ISSUE THREAD

**Issue by albanx** [gruntjs/grunt-contrib-cssmin#243]
Hi 
Running the minification it generates this output css:
``
:after{content:"}

"}
``

expected:

``
:after{content:"}"}
``

this breaks my css. Is this an issue, any workaroud?

Cheers

**Comment by sindresorhus** [comment]
From the top of the readme:

> **Issues with the output should be reported on the clean-css [issue tracker](https://github.com/GoalSmashers/clean-css/issues).**
