### ISSUE TITLE
Reordering and Combining ouput

### ISSUE THREAD

**Issue by azinasili** [gruntjs/grunt-contrib-cssmin#245]
It seems that clean-css now restructures and combines like declarations, in theory this is fantastic however I found it causes slight issues especially with CSS cascading. Is it possible to add an option to turn this feature off?

**Comment by chuddayo** [comment]
I'm having the same issue where, in the minified file, a:hover is now styled before a:visited thereby eliminating the hover effect.

**Comment by sindresorhus** [comment]
This tasks supports any option `clean-css` supports. Would need to be added to `clean-css` first.
