### ISSUE TITLE
Expose zeroUnits clean-css option

### ISSUE THREAD

**Issue by kkirsche** [gruntjs/grunt-contrib-cssmin#247]
`'[+-]properties.zeroUnits' - turn on / off units removal after a 0 value`

https://github.com/jakubpawlowicz/clean-css

X-Ref: twbs/bootstrap#18152 & twbs/bootstrap#18151

**Comment by cvrebert** [comment]
I'm reasonably sure you just have to specify `compatibility: { properties: { zeroUnits: false } }` in the `options` object, which then basically just gets passed on to clean-css.

**Comment by corvae** [comment]
I'm still having an issue with this, using `compatibility: { properties: { zeroUnits: false } }`. `compatibility: "*"` works, but it still removes units for zero values.  I'm just not sure how to add that property.

![cssminerror](https://cloud.githubusercontent.com/assets/7141060/15020314/1e8d7cec-11e7-11e6-9b2a-ef063ea050c6.PNG)

If I force it:

![cssminerror2](https://cloud.githubusercontent.com/assets/7141060/15020573/3284a3aa-11e8-11e6-925b-8cb87dbb0d23.PNG)
