### ISSUE TITLE
how to use: rebase&relativeTo&target 

### ISSUE THREAD

**Issue by chaohuis** [gruntjs/grunt-contrib-cssmin#249]
1.rebase - set to false to skip URL rebasing
2.relativeTo - path to resolve relative @import rules and URLs
3.target - path to a folder or an output file to which rebase all URLs

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
