### ISSUE TITLE
0% is changed to 0, which then defaults to 0px

### ISSUE THREAD

**Issue by krishollenbeck** [gruntjs/grunt-contrib-cssmin#250]
When setting 0% in CSS the % is stripped during the CSS min process. This causes issues when the 0% is intentional. For example we have an odd scenario where a container grows on hover in IE9 and we use this workaround,

```CSS
.ie9Container {
	height: auto;
	min-height:0%;
}
```

This does not work after CSS min though because the % is stripped. I know this is sort of a weird use case, but I think the % should be preserved even if the value is 0. There could possibly be other scenarios where a developer is intentionally setting a CSS property to 0%.

Here is the use case I am referring to. 
http://blog.brianrichards.net/post/6721471926/ie9-hover-bug-workaround

I have also attached an example
[grunt-css-min-test.zip](https://github.com/gruntjs/grunt-contrib-cssmin/files/67002/grunt-css-min-test.zip)

**Comment by sindresorhus** [comment]
From the readme:

> Issues with the output should be reported on the clean-css issue tracker.
