### ISSUE TITLE
Similar class entries are deleted

### ISSUE THREAD

**Issue by cade-galt-1** [gruntjs/grunt-contrib-cssmin#252]
I use the same class name `.blue_but` multiple times.  I do this b.c. each one has a different browser extension and I at one point was parsing the file and targeting my CSS to different browsers.  

To make my life easier I loaded them all in one file, after it was obvious that the browser knows to use the class with its extension.

Can you add an option to allow multiple classes with the same name.  A few others have had a similar issues and requested the same.  See  below.  Thanks.

http://stackoverflow.com/questions/34845819/grunt-contrib-css-is-breaking-my-css-b-c-it-removes-multiple-entries

**Comment by alexVauch** [comment]
Hi there. Maybe try to disable "advanced" [option](https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-api):

```javascript
options: {
   advanced: false
}

**Comment by sindresorhus** [comment]
From the readme:

> Issues with the output should be reported on the clean-css issue tracker.
