### ISSUE TITLE
Performance degradation with Clean-CSS 3.0

### ISSUE THREAD

**Issue by nate250** [gruntjs/grunt-contrib-cssmin#255]
We are experiencing significant performance degradation when upgrading from CSSMin 0.10 to 0.11.
Prior to the upgrade, our main app.css file reduced from 3.73MB to 850kB in roughly 6 seconds.
After the upgrade, the file reduced from 3.73MB to 450kB in 8-10 minutes.

If we run with CleanCSS's advanced option turned off, build time is restored to the more normal 6 seconds, but the file only reduces to 2.99MB.

I assume this is more related to CleanCSS than CSSMin and will be opening an issue there as well.

**Comment by sindresorhus** [comment]
Link up the CleanCSS issue. Nothing we can do about it here.
