### ISSUE TITLE
Fix minification of *zoom

### ISSUE THREAD

**Issue by scottdover** [gruntjs/grunt-contrib-cssmin#256]
It appears that `*zoom` properties (maybe in combination with `expression(...`) do not get minified correctly. 

For example, this file: https://gist.github.com/scottdover/dff60dfa284b4afaaf6f, when ran through grunt-contrib-cssmin generates https://gist.github.com/scottdover/db042ff8dff5d3b5a6c3. 

Basically, anything generated after
```
a [class^="icon-"],
a [class*=" icon-"] {
  cursor: pointer;
}
```
is lost. 

Any help w/ this issue would be greatly appreciated.

**Comment by sindresorhus** [comment]
From the readme:

> Issues with the output should be reported on the clean-css issue tracker.
