### ISSUE TITLE
Compiling produces 'value.indexOf' is not a function

### ISSUE THREAD

**Issue by tigerhawkvok** [gruntjs/grunt-contrib-cssmin#262]
For the following line in a [fairly generic Gruntfile](https://github.com/AmphibiaWeb/amphibian-disease-tracker/blob/d410acb8512dfc1990a2a6cda854d0c1fe58bb1d/Gruntfile.coffee):

``` coffee
    # Other things ...
    cssmin:
      options:
        sourceMap: true
        advanced: false
      target:
        files:
          "css/main.min.css":["css/main.css"]
```

Produces:

``` shell
>grunt cssmin
Running "cssmin:target" (cssmin) task
>> TypeError: value.indexOf is not a function
Warning: CSS minification failed at css/main.css. Use --force to continue.

Aborted due to warnings.
```

Using the most recent Node release:

``` sh
>npm --version
3.8.2
```

And [up-to-date dependencies](https://github.com/AmphibiaWeb/amphibian-disease-tracker/blob/d410acb8512dfc1990a2a6cda854d0c1fe58bb1d/package.json), after running `npm update`, as well.

**Comment by tigerhawkvok** [comment]
I can now update with the fact that disabling Source Maps appears to fix the issue ... which isn't really a fix, of course.

**Comment by tigerhawkvok** [comment]
Filed a PR at https://github.com/jakubpawlowicz/clean-css/pull/751 , but I'll leave the issue open until the PR makes its way into here.

**Comment by XhmikosR** [comment]
It seems that PR was merged.
