### ISSUE TITLE
shorthandCompacting true false doesn't make a difference?

### ISSUE THREAD

**Issue by whats1thingnow** [gruntjs/grunt-contrib-cssmin#265]
hello,

just testing this option shorthandCompacting true false and in my code, it doesn't make a difference...

`options: {
        keepSpecialComments: 0,
        shorthandCompacting: true
          },`

anyone have an example of what this is suppose to do?

thanks :)

**Comment by XhmikosR** [comment]
Please ask for such issues upstream.
