### ISSUE TITLE
EISDIR error 

### ISSUE THREAD

**Issue by zerodburn** [gruntjs/grunt-contrib-cssmin#268]
Just today I started getting this error when compiling any of my projects that use grunt-contrib-cssmin

```
Running "cssmin:target" (cssmin) task

> > Source file ie.css not found
> > Source file login.css not found
> > Source file nomq.css not found
> > Warning: Unable to write "library/css/build" file (Error code: EISDIR). Use --force to continue.

Aborted due to warnings.
```

What's weird is it clearly did find the files, ie.css, login.css and nomq.css because it lists them. I'm using the same syntax as from the documentation example:

```
cssmin: {
  target: {
    files: [{
      expand: true,
      cwd: 'release/css',
      src: ['*.css', '!*.min.css'],
      dest: 'release/css',
      ext: '.min.css'
    }]
  }
}
```

I've been using this for more than a year without any troubles. Now for some reason all of my projects won't compile. I managed to fix it by manually specifying the files, e.g.:

```
cssmin: {
            css:{ 
                files: {
                  'css/build/ie.min.css': ['css/build/ie.css'],
                  'css/build/login.min.css': ['css/build/login.css'],
                  'css/build/nomq.min.css': ['css/build/nomq.css']
                }
            } 
        }
```

It seems really strange that this would suddenly happen. I'm using Windows 10, I didn't run npm update or anything.

**Comment by truckingsim** [comment]
Can confirm, having same problem.  Manual fix listed above also made it work for me.  I'm using Ubuntu 14.04.  I had just installed this plugin today.

**Comment by XhmikosR** [comment]
Something else is keeping the handle open; antivirus software etc.
