### ISSUE TITLE
feature request - option to delete (single) source file once compiled

### ISSUE THREAD

**Issue by StudioSpindle** [gruntjs/grunt-contrib-cssmin#275]
Would it be an idea to add the option to delete the source file if you're minifying from one single file? 

I have a specific use case where I compile multiple SASS source files into a uncompiled css file. Then with css min I minifiy the file for a production task and add a '.min' to the filename.

**Comment by sKopheK** [comment]
dunno if I understand your problem right, but you can use other grunt tasks to remove any files you want

**Comment by XhmikosR** [comment]
You can achieve this with http://gruntjs.com/api/grunt.file#grunt.file.delete or other plugins.
