### ISSUE TITLE
require more elaborative errors

### ISSUE THREAD

**Issue by ashish-joshi-sr** [gruntjs/grunt-contrib-cssmin#276]
when i run the task.. it had error displaying below lines

```
Running "cssmin:target" (cssmin) task
>> unexpeced content : '
>> }'. Ignoring.
>> 1 file created.
```

but the produced minified css had lot of issues.
can you please add that in which file and which line it encountered issue? so I can look for it.

**Comment by XhmikosR** [comment]
I believe such issues should be reported upstream.

Also, the next version which will use clean-css v4.0.0 might solve this.
