### ISSUE TITLE
Converting negative z-index to positive on minification

### ISSUE THREAD

**Issue by binho500** [gruntjs/grunt-contrib-cssmin#279]
When minifying  .CSS the engine converts negative z-Index to positive.
Example:
**Original CSS:**
```
.backLogo{
    position:absolute;
    bottom: 10px;
    right:15px;
    opacity: 0.4;
    z-index: -1;
}
```
**Minified:**
`.backLogo{position:absolute;bottom:10px;right:15px;opacity:.4;z-index:1}`

According to W3C, negative z-Index are allowed:

> number	Sets the stack order of the element. Negative numbers are allowed

http://www.w3schools.com/cssref/pr_pos_z-index.asp

**Comment by XhmikosR** [comment]
Such issues should be reported upstream.
