### ISSUE TITLE
Newer versions not on NPM

### ISSUE THREAD

**Issue by franz-josef-kaiser** [gruntjs/grunt-contrib-cssmin#283]
While the last tag here is `2.0.0`, the last tag on NPM is `1.0.2`. Could someone please push the tags? Thanks a bunch!

In the meantime, one can install from source/GitHub directly:

    "devDependencies" : { "grunt-contrib-cssmin" : "gruntjs/grunt-contrib-cssmin" }

**Comment by XhmikosR** [comment]
This is no longer an issue.
