### ISSUE TITLE
TypeError: Object #<Object> has no method 'isAbsolute'

### ISSUE THREAD

**Issue by dydrema** [gruntjs/grunt-contrib-cssmin#286]
what i can do now?

**Comment by XhmikosR** [comment]
Make sure you are using the latest clean-css version and otherwise report the issue upstream.

**Comment by mjj2000** [comment]
The API `path.isAbsolute` is available in node.js `v0.11.2+`. Upgrading node.js can fix this issue.

https://nodejs.org/api/path.html#path_path_isabsolute_path
