### ISSUE TITLE
bad css if declaring classes with word "null"

### ISSUE THREAD

**Issue by nicolaelitvac** [gruntjs/grunt-contrib-cssmin#287]
This css :
`.page__section--padding-null { padding: 0; }
.page__section--padding-top-null { padding-top: 0; }
.page__section--padding-bottom-null { padding-bottom: 0; }`

Is transformed into :
`.page__section--padding-$1 $2]{padding:0}.page__section--padding-top-$1 $2]{padding-top:0}.page__section--padding-bottom-$1 $2]{padding-bottom:0}`

Word "**null**" appears as "**$1 $2]**".

**Comment by mqliao** [comment]
+1, Please fix this issue
input:
.record-null{color:#aaa;}
output:
.record-$1 $2]{color:#aaa}

**Comment by XhmikosR** [comment]
Issues with the output should be reported on the clean-css [issue tracker](https://github.com/jakubpawlowicz/clean-css/issues).
