### ISSUE TITLE
cssmin generate CSS larger than before

### ISSUE THREAD

**Issue by KBuenoDev** [gruntjs/grunt-contrib-cssmin#288]
Hi, I have the following configuration

        cssmin: {
            target: {
                files: [{
                    expand: true,
                    cwd: 'assets/css',
                    src: ['*.css', '!*.min.css'],
                    dest: 'cssmin',
                    ext: '.min.css'
                }]
            }
        },

but generate css larger than before of 22 KB to 44 KB, someone is have a idea why is this happening?

**Comment by XhmikosR** [comment]
It's the new clean-css defaults. Either way this is an upstream question.
