### ISSUE TITLE
cssmin fails with @page

### ISSUE THREAD

**Issue by julmot** [gruntjs/grunt-contrib-cssmin#289]
Does anyone of you know why this code fails?

![2017-05-22 17_57_24-mark js - p__open-source_mark js - p__eurocentres_drupal_sites_all_themes_ec_r](https://cloud.githubusercontent.com/assets/8310677/26317602/5334f3d0-3f18-11e7-8b35-fdddc6abc7b2.png)

**Comment by helmutgranda** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@page

Formal syntax

```css
@page <page-selector-list> {
  <page-body>
}
```

**Comment by XhmikosR** [comment]
> Issues with the output should be reported on the clean-css issue tracker.
