### ISSUE TITLE
Object has no method 'expandFiles'

### ISSUE THREAD

**Issue by ilanbiala** [gruntjs/grunt-contrib-cssmin#29]
Before I even got this error to print out, the npm installed the grunt plugin as 'grunt-contrib-mincss' however the readme.md shows that it should be 'grunt.loadNpmTasks('grunt-contrib-cssmin');' which didn't work, so I had to switch it to 'mincss' at the end to match the plugin.

The main problem I am having, which others suggest is because the plugin may not have been updated fully yet, is that I get the error 'Warning: Object #<Object> has no method 'expandFiles' Use --force to continue.'

The code that I am trying to get working and that ultimately causes this error is

```
mincss: {
  files: {
    src: ['src/**/*.css'],
    dest: 'build/'
  }
}
```

**Comment by tiveor** [comment]
it works for me too. Thanks.
