### ISSUE TITLE
Plugin removes media queries

### ISSUE THREAD

**Issue by helmutgranda** [gruntjs/grunt-contrib-cssmin#290]
Has anyone run into the issue where the media queries are removed? This only happens with specific files under a folder on Windows machine, all remaining files stay intact. 

I have opted out for using grunt-contrib-concat and use cssnano to minify the file.

I have updated my dependencies, removed/added back files without mixed results, so far using concat and cssnano works as expected.

Anyone else running into a similar issue?

**Comment by XhmikosR** [comment]
> Issues with the output should be reported on the clean-css issue tracker.
