### ISSUE TITLE
Css minification is not working for bootstrap-sass-official in Jenkins.

### ISSUE THREAD

**Issue by medaamarnadh** [gruntjs/grunt-contrib-cssmin#293]
Hi I am using grunt-contrib-cssmin for minification. I am also using sass. 
Its not working for me in Jenkins. It showing below error.

```{"line":5,"column":2081},"source":"../../bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins/_buttons.scss","original":{"line":38,"column":-10},"name":null}```

Can any one have a solution for this?

**Comment by XhmikosR** [comment]
Issues with the output should be reported on the clean-css issue tracker.
