### ISSUE TITLE
failed when compress css with @charset "utf-8"

### ISSUE THREAD

**Issue by mamayan** [gruntjs/grunt-contrib-cssmin#294]
when I was compressing css file which started with @charset "utf-8",failed and throw error "invalid selector @charset "utf-8",system is window7 pro

**Comment by varataharaj** [comment]
getting this error "Ignoring Invalid selector '@charset 'utf-8';" If I have the charset value in my css file.

**Comment by XhmikosR** [comment]
> Issues with the output should be reported on the clean-css issue tracker.
