### ISSUE TITLE
Script breaks on @import from css comment

### ISSUE THREAD

**Issue by robhrt7** [gruntjs/grunt-contrib-cssmin#42]
I have a comment like this, in one of my css files

/*
- Here you can add your site (project) CSS files @import for use with spec pages examples
  */

Where CSS @import is parsed by script and gives an error

```
>> Error: Broken @import declaration of "for"
```

**Comment by horka** [comment]
I have also met the problem, when I have used absolute paths instead of relative paths. I did not check out yet why it happens, however a `path.relative(__dirname, <path>)` solved the problem for me temporarily. Maybe it helps anybody.
